# Site
repository: RenzYumul
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Renz Yumul
title: Computer Science Student | Graphic Designer
email: RYumul24-0597@cca.edu.ph
phone: +639165947084
website: https://renzyumul.github.io

# Dark Mode
darkmode: true

# Social links
github_username: Rpy101014
linkedin_username: renzcs
instagram_username: _laurelpineda
twitter_username: 
facebook_username: 
youtube_username: 
stackoverflow_username: 
dribbble_username: 
flickr_username: 
xing_username: 
pinterest_username: 
orcid_username: 
googlescholar_username: 

# Additional icon links
#additional_links:
#- title: Portfolio
#  icon: fas fa-globe
#  url: https://renzcs.github.io
#- title: TikTok Bass Covers
#  icon: fab fa-tiktok
#  url: https://www.tiktok.com/@renz_bass

# About Section
#about_profile_image: images/profile.jpg
about_content: |
  I'm a **Computer Science student** and **graphic designer** with a passion for technology, automation, and creative problem-solving. I thrive at the intersection of **hardware, software, and design**, working on projects that range from **embedded systems with ESP32/Arduino** to **UI-focused designs** and **bass music production**.

  - Strong interest in **system optimization**, **low-level programming**, and **containerization** (Docker/Kubernetes).
  - Skilled in **graphic design**, **electronics prototyping**, and **automating workflows**.
  - Current goal: Build a foundation for **IT infrastructure and sysadmin roles** while finishing my CS degree.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        border: weak
        title: Automated Label Proof System
        link: 
        link_text: 
        additional_links:
          - title: GitHub Repo
            icon: fab fa-github
            url: https://github.com/renzCS
        quote: >
          A custom automation solution to streamline order-proof workflows.
        description: |
          Developed scripts and automation pipelines to reduce manual intervention in printing and design processes, improving turnaround time and accuracy for a US-based client.

      - layout: left
        border: weak
        title: IoT-Based ESP32 Prototypes
        link: 
        link_text: 
        additional_links:
          - title: GitHub Repo
            icon: fab fa-github
            url: https://github.com/renzCS
        quote: >
          Building low-level firmware and connected systems.
        description: |
          Designed and implemented IoT solutions with ESP32 and Teensy boards, integrating sensors and microcontrollers to demonstrate real-world hardware/software synergy.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: US-based Printing Company
        sub_title: Graphic Designer & Automation Specialist
        caption: 2023 - Present
        quote: >
          A leading provider of custom print solutions.
        description: |
          - Managed and proofed custom label and sticker designs for global clients.
          - Developed scripts and actions to automate redundant processes, reducing operational bottlenecks.
          - Maintained a customer-focused workflow ensuring quality and turnaround adherence.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: [Your University Name]
        sub_title: Bachelor of Science in Computer Science
        caption: 2023 - Present
        description: |
          Coursework includes **Data Structures**, **Algorithms**, **Systems Programming**, and **Computer Organization**.  
          Current focus on **containerization**, **microservices**, and **embedded systems** for future infrastructure and DevOps roles.

  - title: A Little More About Me
    layout: text
    content: |
      **Interests**  
      - Low-level programming, OS kernel development  
      - Automation and IT Infrastructure  
      - Digital & Analog Electronics  
      - Bass guitar performance and music production  

      **Skills**  
      - Languages: C, C++, Python  
      - Tools: Docker, Git, Adobe Suite  
      - Platforms: Arduino, ESP32, Teensy, Raspberry Pi  

# Footer
footer_show_references: true
references_title: References available on request

# Build settings
remote_theme: sproogen/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
